### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by mikezander**
Changed post to past on line 10 of the repo's description.

### CODE REVIEW

**Comment by evgenyneu** [comment]
Thanks @mikezander, but what I meant by "post those inescapable 1-star reviews " is that users can **submit** these reviews. Should I change it to "submit" to make it clearer?

**Comment by mikezander** [comment]
@evgenyneu Oh I see what you meant, I think it should be "to post" then.

**Comment by evgenyneu** [comment]
Yes, I agree. You can change it in your pull request if you want.

**Comment by mikezander** [comment]
Cool I just fixed it 👍

**Comment by evgenyneu** [comment]
Thank you very much!

**Pull request merged**
