### PR TITLE
add PrivacyInfo podspec, Package

### PR DESCRIPTION
**Pull request by wlxo0401**
add PrivacyInfo podspec, Package

Feel free to give me your opinion.

### CODE REVIEW

**Comment by wlxo0401** [comment]
Discussion Reference - https://github.com/evgenyneu/Cosmos/issues/198

**Comment by evgenyneu** [comment]
Thanks

**Comment by wlxo0401** [comment]
@evgenyneu 

Happy New Year!

**Comment by evgenyneu** [comment]
You too

**Pull request merged**
