### PR TITLE
Added new property  - useful when  is added to a view controller that…

### PR DESCRIPTION
**Pull request by benpackard**
Fix for https://github.com/evgenyneu/Cosmos/issues/148

### CODE REVIEW

**Comment by evgenyneu** [comment]
Thank you very much! Excellent work. I've released your changes in version `20.0.1`. Please let me know if there are still any issues.

**Comment by benpackard** [comment]
Oh dear - I seem to have missed something somewhere. Once I updated to `20.0.1` and set the new flag `disablePanGestures` to `true` there is no change in behavior in my app.

It seems that `gestureRecognizerShouldBegin` is never called. Which is strange, because when I subclass `CosmosView` and override it, it *is* called. In other words, this works:

```
private class FixedCosmosView: CosmosView {
	override func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
		print("gesture") // this is printed
	}
}
```

But this (the implementation used in recent commit) does not:

```
@IBDesignable open class CosmosView: UIView {
...
    override func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
		print("gesture")
    }
...
}
```

I'm not sure why it would work in a subclass, but not in the `CosmosView` class itself.

**Comment by evgenyneu** [comment]
Hmm, that's good to know. I've made a demo and it seems to work for me (tried both with simple file installation and CocoaPods):

[CosmosModalDemo.zip](https://github.com/evgenyneu/Cosmos/files/3678611/CosmosModalDemo.zip)

Let me know if the demo works for you. Maybe there is something else that is causing the issue?

By the way, in your code example above, I noticed that you wrote `gestureRecognizerShouldBegin` without `open`:

```Swift
open override func gestureRecognizerShouldBegin...
```

I can see that [we use `open` currently](https://github.com/evgenyneu/Cosmos/blob/0ce74de64fdb6bfb19a7090f9d5f1fc5288bfbf6/Cosmos/CosmosView.swift#L286). Is that code snippet above taken from `20.0.1` code?

**Comment by benpackard** [comment]
Thanks for the demo, I can confirm that it works for me so now I'm going through my own project to see what differs.

As for the snippet, the second piece of code is just a quick log statement I used to see if the delegate function is even called. I replaced the same function in `20.0.1` and found that nothing is logged when I use the CosmosView. Whereas when I subclass and override, the log appears. Very strange.

Perhaps something to do with the fact I am adding it programmatically vs using a storyboard. Hopefully I will have some more information soon.

The good news at least is that the commit added in 20.0.1 is fit for purpose.

**Comment by evgenyneu** [comment]
> Perhaps something to do with the fact I am adding it programmatically vs using a storyboard. Hopefully I will have some more information soon.

That's possible. I think we can test this by modifying my demo and create cosmos view programmatically.

**Comment by benpackard** [comment]
Yep. I’ll also try to test inside a scroll view and inside a navigation
controller etc.

**Comment by benpackard** [comment]
I'm sorry for the confusion - this morning with a clear head I went back to basics and cleaned all my build folders and derived data and now everything is working well. 

Thanks for helping me figure it out and for merging the PR, which seems to work well in my project!

**Comment by evgenyneu** [comment]
No worries, I'm glad that it's working for you now. The caching of stuff in Xcode can be frustrating.

**Pull request merged**
